#!/bin/bash

#SBATCH -n 1
#SBATCH --cpus-per-task=256
#SBATCH --mem=550g
#SBATCH -t 18:00:00
#SBATCH --mail-type=begin,end,fail
#SBATCH --mail-user=arijitm@unc.edu

source /nas/longleaf/home/arijitm/miniconda3/etc/profile.d/conda.sh
conda activate gtdbtk-2.6.1
gtdbtk classify_wf --genome_dir /users/a/r/arijitm/genomes_dangl_lab/final_list_screen --out_dir /users/a/r/arijitm/genomes_dangl_lab/final_list_screen/classify_out --cpus 256

#Use the classify output as an input for FastTree
conda activate fasttree
FastTree -wag -gamma gtdbtk.bac120.msa.fasta > tree_wag.nwk
